## Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
##

def evenFibonacchi(maximum)
  low = 1
  high = 1
  sum = 2
  count = 0
  while sum < maximum
    if sum % 2 == 0
      count = count + sum
    end
    low = high
    high = sum
    sum = low + high
  end
  puts ""
  puts "Sum of even Fibonacci numbers: "
  puts count.to_s
end

puts ""
puts "Returns sum of all even valued Fibonacci numbers between 1 and maximum."
puts "Enter Maximum: "
number = gets.chomp
evenFibonacchi(number.to_i)
# returns 4613732
